# Generated by Django 5.2.17 on 2026-09-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("demo", "Book a demo"),
                            ("contact", "General question"),
                            ("migration", "Free migration"),
                            ("partner", "Partnership"),
                            ("investor", "Investor enquiry"),
                        ],
                        default="demo",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("business_name", models.CharField(blank=True, max_length=120)),
                ("facebook_page", models.URLField(blank=True)),
                ("category", models.CharField(blank=True, max_length=60)),
                ("message", models.TextField(blank=True)),
                ("handled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("slug", models.SlugField(unique=True)),
                ("tagline", models.CharField(max_length=120)),
                (
                    "price_monthly",
                    models.PositiveIntegerField(help_text="Price in BDT per month"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Blank = unlimited", null=True
                    ),
                ),
                (
                    "ai_listings_per_month",
                    models.PositiveIntegerField(
                        blank=True, help_text="Blank = unlimited", null=True
                    ),
                ),
                (
                    "staff_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Blank = unlimited", null=True
                    ),
                ),
                ("custom_domain", models.BooleanField(default=False)),
                ("features", models.TextField(help_text="One feature per line")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
