# Generated by Django 5.2.17 on 2026-09-27 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                (
                    "percent_off",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("amount_off", models.PositiveIntegerField(blank=True, null=True)),
                ("min_order", models.PositiveIntegerField(default=0)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=240)),
                ("city", models.CharField(blank=True, max_length=60)),
                ("phone_verified", models.BooleanField(default=False)),
                ("loyalty_points", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("packed", "Packed"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cod", "Cash on delivery"),
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("sslcommerz", "Card / SSLCommerz"),
                        ],
                        default="cod",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partial", "Advance paid"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=60)),
                (
                    "courier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pathao", "Pathao"),
                            ("steadfast", "Steadfast"),
                            ("redx", "RedX"),
                            ("self", "Own delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tracking_code", models.CharField(blank=True, max_length=60)),
                ("shipping_name", models.CharField(max_length=120)),
                ("shipping_phone", models.CharField(max_length=20)),
                ("shipping_address", models.CharField(max_length=240)),
                ("shipping_city", models.CharField(max_length=60)),
                ("inside_dhaka", models.BooleanField(default=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "advance_required",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                ("otp_verified", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("store", "Website"),
                            ("messenger", "Messenger"),
                            ("whatsapp", "WhatsApp"),
                            ("manual", "Manual"),
                        ],
                        default="store",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stores.coupon",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="stores.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                (
                    "title_bn",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Title (Bangla)"
                    ),
                ),
                ("slug", models.SlugField(max_length=160)),
                ("sku", models.CharField(blank=True, max_length=40)),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_bn",
                    models.TextField(blank=True, verbose_name="Description (Bangla)"),
                ),
                (
                    "highlights",
                    models.TextField(blank=True, help_text="One highlight per line"),
                ),
                (
                    "variants",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated, e.g. S, M, L",
                        max_length=200,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma separated", max_length=240
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=170)),
                ("is_active", models.BooleanField(default=True)),
                ("ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="stores.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("variant", models.CharField(blank=True, max_length=60)),
                ("unit_price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stores.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in your free subdomain", unique=True
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=140)),
                ("category", models.CharField(blank=True, max_length=60)),
                ("logo", models.ImageField(blank=True, upload_to="logos/")),
                ("brand_color", models.CharField(default="#1E7F5C", max_length=7)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("bazaar", "Bazaar"),
                            ("minimal", "Minimal"),
                            ("boutique", "Boutique"),
                        ],
                        default="bazaar",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("facebook_url", models.URLField(blank=True)),
                ("custom_domain", models.CharField(blank=True, max_length=120)),
                ("delivery_fee_dhaka", models.PositiveIntegerField(default=60)),
                ("delivery_fee_outside", models.PositiveIntegerField(default=120)),
                (
                    "advance_threshold",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Ask for delivery-fee advance when the risk score is at or above this (0–100)",
                    ),
                ),
                ("otp_checkout", models.BooleanField(default=True)),
                (
                    "enabled_payments",
                    models.CharField(default="cod,bkash,nagad", max_length=80),
                ),
                (
                    "enabled_couriers",
                    models.CharField(default="pathao,steadfast,redx", max_length=80),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_live", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="stores.store",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("store", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("store", "phone")},
        ),
        migrations.AlterUniqueTogether(
            name="coupon",
            unique_together={("store", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("store", "slug")},
        ),
    ]
